#!/bin/bash
# Bundle Carrie's Meridian (app.py + data) into an OpenClaw skill, install it into the
# sandbox, and add a routing rule to AGENTS.md so deal questions always go through it.
# Re-run after changing app.py, meridian_format.py, data/meridian/ or data/roles.json.
set -euo pipefail
cd "$(dirname "$0")/.."
SANDBOX="${1:-my-assistant}"
WS=/sandbox/.openclaw/workspace
SKILL_DIR="$WS/skills/meridian"

BUILD="$(mktemp -d)/meridian"
trap 'rm -rf "$(dirname "$BUILD")"' EXIT
mkdir -p "$BUILD/data/meridian"
cp skills/meridian/SKILL.md skills/meridian/meridian_cli.py app.py meridian_format.py "$BUILD/"
cp data/meridian/resources.json "$BUILD/data/meridian/"
cp data/roles.json "$BUILD/"

# Smoke-test the bundle on the host before shipping it.
python3 -I "$BUILD/meridian_cli.py" --sender U0C675Y48CR --channel agenda >/dev/null

nemoclaw "$SANDBOX" skill install "$BUILD"

nemoclaw "$SANDBOX" exec -- sh -c "
  set -e
  cd $WS
  sed -i '/<!-- meridian-routing:start/,/<!-- meridian-routing:end -->/d' AGENTS.md
  cat >> AGENTS.md <<'EOF'

<!-- meridian-routing:start (generated by skills/install_meridian_skill.sh — do not edit by hand) -->
## Meridian deal questions

Any question about the deal — meeting agenda, approved documents, financials / revenue / EBITDA / margin,
the 96m vs 106m offer, board memo or walk-away price, verifying data or signatures, customers or contract
values — MUST be answered by running this with the \`exec\` tool (no other tool, no answering from memory):

    python3 $SKILL_DIR/meridian_cli.py --sender <SENDER_SLACK_ID> --dm|--channel \"<question verbatim>\"

Use the sender's Slack user ID from message metadata, \`--dm\` for direct messages and \`--channel\` for shared
channels. Reply with the script output as-is; never add numbers or documents it did not return, never soften a DENY.
<!-- meridian-routing:end -->
EOF
  grep -c 'meridian-routing' AGENTS.md
"
