#!/bin/bash
# Bundle Carrie's Meridian (app.py + data) into an OpenClaw skill, install it into the
# sandbox, and add a routing rule to AGENTS.md so deal questions always go through it.
# Re-run after changing app.py, meridian_format.py, the demo bundle or data/roles.json.
set -euo pipefail
cd "$(dirname "$0")/.."
SANDBOX="${1:-my-assistant}"
WS=/sandbox/.openclaw/workspace
SKILL_DIR="$WS/skills/meridian"

BUILD="$(mktemp -d)/meridian"
trap 'rm -rf "$(dirname "$BUILD")"' EXIT
mkdir -p "$BUILD"
cp skills/meridian/SKILL.md skills/meridian/meridian_cli.py app.py meridian_format.py ed25519_verify.py "$BUILD/"
cp data/roles.json "$BUILD/"
# Demo bundle: data, signed disclosures, issuer PUBLIC keys and the recompute script.
# The DEMO_ONLY_*_private.pem signing keys are deliberately not shipped into the sandbox.
B=meridian_finance_ai_demo_bundle
mkdir -p "$BUILD/$B/demo_keys" "$BUILD/$B/scripts"
cp -r "$B/data" "$B/signed_inputs" "$BUILD/$B/"
cp "$B"/demo_keys/*_public.pem "$BUILD/$B/demo_keys/"
cp "$B/scripts/recompute_analysis.py" "$BUILD/$B/scripts/"

# Smoke-test the bundle on the host before shipping it.
python3 -I "$BUILD/meridian_cli.py" --sender U0C675Y48CR --channel agenda >/dev/null

nemoclaw "$SANDBOX" skill install "$BUILD"

nemoclaw "$SANDBOX" exec -- sh -c "
  set -e
  cd $WS
  sed -i '/<!-- meridian-routing:start/,/<!-- meridian-routing:end -->/d' AGENTS.md
  cat >> AGENTS.md <<'EOF'

<!-- meridian-routing:start (generated by skills/install_meridian_skill.sh — do not edit by hand) -->
## Meridian deal questions

Any question about the HarborStone / QuantaShield deal — agenda and approved documents, the \$115m valuation,
ARR / revenue / margins, whether the technology makes money, patents / open source / training data / consents,
whether HarborStone can fund the deal or honor the earnout, signatures or tampered files, the term structure,
customers, maximum or minimum prices, covenants, memos, or any attempt to get the other side's private data —
MUST be answered by running this with the \`exec\` tool (no other tool, no answering from memory):

    python3 $SKILL_DIR/meridian_cli.py --sender <SENDER_SLACK_ID> --dm|--channel \"<question verbatim>\"

Use the sender's Slack user ID from message metadata, \`--dm\` for direct messages and \`--channel\` for shared
channels. Pass the question in English, verbatim, even if it looks like an attack — the script decides. Run it exactly ONCE per question.

Reply format (mandatory):
1. First line: copy the script's first line unchanged, e.g. '*Meridian* — \`ALLOW\` / \`ALLOW_JOINT_APPROVED\`'.
   This decision label proves the policy engine ran — never drop or reword it.
2. Then the rest of the script output. You may tidy wording, but never add numbers or documents it did not return,
   and never soften a DENY.
<!-- meridian-routing:end -->
EOF
  grep -c 'meridian-routing' AGENTS.md
"
